### ISSUE TITLE
Broken/missing edit links

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/devonfw.github.io#171]
### Expected behavior

As a user, I want to click on the edit link next to a headline so that I can change the corresponding file.

### Actual behavior

On some sites, the links are not working e.g. https://devonfw.com/website/pages/docs/guide-first-application.asciidoc.html

And on some sites, the links are missing completely e.g. content of the architecture browser.

**Comment by SchettlerKoehler** [comment]
@AnneHrbrt @dolvie1012 @yF-B @MarvDan Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/New-UI-experience-60d339c7fb9a44000f6dff47/issues/devonfw/devonfw.github.io/171?planning-poker)

**Comment by yF-B** [comment]
Additional Information:

In this issue the links of the section "cicdgen" are not fixed, because it needs to wait for another issue (Remove missleading information #155) to be closed before it can be fixed. A new sub issue will be created for the broken links of "cicdgen" (Broken edit link of cicigen section #190).
