### ISSUE TITLE
Add pencil do architecture browser

### ISSUE THREAD

**Issue by maybeec** [devonfw/devonfw.github.io#203]
As a reader, I want contribute easily to the architecture browser so that I can fix small issues or propose new changes.

Therefore it would be great, if we would be able to add the pencil like in the docs section here as well.

**Comment by tobka777** [comment]
I did a fix for the pencil in the architecture page. I also added the pencil to h2, that is the headline and for me this is useful, but maybe not optimal in general.

**Comment by tobka777** [comment]
During the test of all links, I noticed that the folders in my `architectures/solution` are not the same as in the architectures repository (https://github.com/devonfw/architectures). This corresponds to wrong links for `microsvc_platforms_azure` (instead of microsvc_platforms) and `provisioning_azure_devops` (instead of `provisioning_azure_azuredevops`). -> #227
