### ISSUE TITLE
videos are not loaded on the deployed page

### ISSUE THREAD

**Issue by maybeec** [devonfw/devonfw.github.io#4]
see https://www.devonfw.com/devonfw-official-website/website/pages/logo/page-logo.html

**Comment by jambulud** [comment]
This problem is related with docgen.
When you add an image or a video, the source is set using the absolute in which "mvn package ..." is run so:

* If you run it in your local machine you will have something like:
`<video src="C://.../video-name">`

* In travis:
` <video src = "/home/.../video-name"`

The same occur with images, furthermore this is the reason behind why sometimes the images are not loaded. In images we solve this replacing the src with a relative path and we could follow a similar aproach in videos.
Check  https://github.com/devonfw/devonfw-official-website/blob/f2fb31e5ce9e38f975598801d569f327177e6ce6/website/config/devonfw-site-conf.js#L61

**Comment by maybeec** [comment]
And why are some of the images not show now? As I understood you right, for images you already implemented the path conversion.

**Comment by jambulud** [comment]
Which images? I have checked and I'm seeing all the images in the website
Images not displayed errors may come from a different source, for instance typographical errors

**Comment by maybeec** [comment]
tage the devon logo as an example on the top left.

**Comment by jambulud** [comment]
It is because <img> tags don't like .svg images as src value and the most inmediate solution is changing it to png. Pablo is currently working on it.

This problem with .svg images doesn't happend if it is set as background-image

https://www.w3.org/Graphics/SVG/IG/resources/svgprimer.html#SVG_in_HTML

**Comment by maybeec** [comment]
could you ask pablo to track his work by assigning himself to this ticket and track it on zenhub?

**Comment by jambulud** [comment]
Yes, of course

**Comment by jambulud** [comment]
The task pablo is working on is the top left icon, not the video problem
